    CREATE TABLE Docente (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2 (255) NOT NULL,
        email VARCHAR2(255) UNIQUE NOT NULL,
        telefone VARCHAR2(20),
        senha VARCHAR2(255) NOT NULL
    );
    
    CREATE TABLE Instituicao (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(255) NOT NULL,
        id_docente INT NOT NULL,  
        FOREIGN KEY (id_docente) REFERENCES Docente(id)
    );
    
    CREATE TABLE Disciplina (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(255) NOT NULL,
        sigla VARCHAR2(20),
        codigo VARCHAR2(20),
        periodo VARCHAR2(50),
        tipo_calculo VARCHAR2(20) NOT NULL,  
        id_instituicao INT NOT NULL,
        FOREIGN KEY (id_instituicao) REFERENCES Instituicao(id)
    );
    
    CREATE TABLE Turma (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(255) NOT NULL,
        codigo VARCHAR2(50),
        apelido VARCHAR2(100) NOT NULL,
        id_disciplina INT NOT NULL,
        FOREIGN KEY (id_disciplina) REFERENCES Disciplina(id)
    );
    
    CREATE TABLE Aluno (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        matricula VARCHAR2(50) UNIQUE NOT NULL,
        nome VARCHAR2(255) NOT NULL
    );
    
    CREATE TABLE TurmaAluno (
        id_turma INT NOT NULL,
        id_aluno INT NOT NULL,
        PRIMARY KEY (id_turma, id_aluno),
        FOREIGN KEY (id_turma) REFERENCES Turma(id),
        FOREIGN KEY (id_aluno) REFERENCES Aluno(id)
    );
    
    CREATE TABLE Componente (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(255) NOT NULL,
        sigla VARCHAR2(20),  
        descricao CLOB,
        peso NUMBER(4,2),  
        id_disciplina INT NOT NULL,
        FOREIGN KEY (id_disciplina) REFERENCES Disciplina(id)
    );
    
    CREATE TABLE Nota (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_aluno INT NOT NULL,
        id_componente INT NOT NULL,
        valor NUMBER(4,2) NOT NULL,
        FOREIGN KEY (id_aluno) REFERENCES Aluno(id),
        FOREIGN KEY (id_componente) REFERENCES Componente(id) 
    );
    
    CREATE TABLE AuditoriaNota (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_docente INT NOT NULL,  
        id_aluno INT NOT NULL,  
        id_componente INT NOT NULL,
        data_hora TIMESTAMP NOT NULL,
        descricao CLOB,  
        FOREIGN KEY (id_docente) REFERENCES Docente(id),
        FOREIGN KEY (id_aluno) REFERENCES Aluno(id),
        FOREIGN KEY (id_componente) REFERENCES Componente(id)
    );
    FOREIGN KEY (id_aluno) REFERENCES Aluno(id),
    FOREIGN KEY (id_componente) REFERENCES Componente(id)
);

